### ISSUE TITLE
Missing entries for acorns:flour-acorn in multiple recipes

### ISSUE THREAD

**Issue by PhyDoesStuff** [l33tmaan/vs-expandedfoods#15]
Log entries in server-main.txt indicate that multiple recipes are missing entries for `acorns:flour-acorn` in
- expandedfoods:recipes/kneading/acorns/acornbreadedball.json
- expandedfoods:recipes/kneading/wildcraft/herbstuff/breadedfishnuggetherb.json
- expandedfoods:recipes/kneading/wildcraft/herbstuff/herbalstuffedpepper.json
- expandedfoods:recipes/kneading/wildcraft/herbstuff/wildherbbreadedball.json
- expandedfoods:recipes/kneading/wildcraft/herbstuff/wildherbbreadedfishnugget.json
- expandedfoods:recipes/kneading/wildcraft/herbstuff/wildherbbreadedmeatnugget.json
- expandedfoods:recipes/kneading/wildcraft/herbstuff/wildherbbreadedvegetable.json
- expandedfoods:recipes/kneading/breadstarter.json

I've attached server-main.txt for review: [server-main.txt](https://github.com/l33tmaan/vs-expandedfoods/files/8882767/server-main.txt)

**Comment by l33tmaan** [comment]
Should be fixed in 1.5.3.

**Comment by PhyDoesStuff** [comment]
Unfortunately, I'm still seeing most of these in 1.5.3.

`breadstarter.json` and `acornbreadedball.json` are the only ones that have been resolved.

I've included a new server-main.txt, the Warnings start on line 235 and continue until line 605 (lots of repeats lines, I'd guess for variant recipes).

[server-main.txt](https://github.com/l33tmaan/vs-expandedfoods/files/8985459/server-main.txt)

**Comment by l33tmaan** [comment]
Thanks for the heads up. I'm messing around with those recipes right now, actually. Shouldn't be too hard to fix, just... tedious and slightly confusing.

**Comment by l33tmaan** [comment]
This should be fixed in the upcoming release.
